### PR TITLE
Add the ability to store encrypted JIRA passwords

### PR DESCRIPTION
**Pull request by kevinjqiu**
Our ops are not comfortable with the JIRA password (which happens to be our active directory password) sitting in our home folder unencrypted. This PR adds the ability to encrypt the JIRA password with a passphrase using scrypt.

Let me know what you think :)

### CODE REVIEW

**Comment by coddingtonbear** [comment]
I really wish you'd mentioned this in the channel a little earlier -- I've been planning to add a feature allowing you to store your JIRA password in your system keyring.

**Comment by kevinjqiu** [comment]
@coddingtonbear no worries.  System keyring is probably a better place to put it.  Feel free to close this PR.

**Comment by coddingtonbear** [comment]
But you put so much effort into this, @kevinjqiu!  I'm really, really, sorry for not having posted something about my vague plans somewhere :-/.

In the future, though, I wonder if I could convince you saying hello in the [gitter channel](https://gitter.im/coddingtonbear/jirafs) before getting too far on something so you don't spend *too* much time on a feature that'd be difficult to get merged.

Forgive me and thank you for understanding, and I'll try to get the keyring thing hammered out over the next couple of days.

**Comment by kevinjqiu** [comment]
@coddingtonbear No problems :)  I didn't spend too much time on this.  I'll join the channel if I have some feature in mind :)

**Pull request closed without merging**
